In [1]:
import numpy as np
from keras import models;

In [4]:
from gtda.graphs import GraphGeodesicDistance

# Попытка
Исследовать структуру нейронной сети как граф. Испробованы 
- Комплекс Виеториса-Рипса
- FlagsterPersistence

## Load model

In [179]:
firstSize, secondSize, outputSize = 10, 10, 1
cut_by = 1
modelDir = "./models/"
model_name = modelDir + "first"+str(firstSize)+"second"+str(secondSize)+"output"+str(outputSize) + "cut_by" + str(cut_by) + ".h5"

In [17]:
print(model_name)

./first10second10output1cut_by1.h5


In [18]:
model = models.load_model(model_name, compile = False)

In [19]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 10)                160       
                                                                 
 dense_4 (Dense)             (None, 10)                110       
                                                                 
 dense_5 (Dense)             (None, 1)                 11        
                                                                 
Total params: 281
Trainable params: 281
Non-trainable params: 0
_________________________________________________________________


In [161]:
from scipy.sparse import csr_matrix

def get_relevance(model, outputSize = 1):
    n = len(model.layers) - 1
    layers = model.layers[1:]
    weights = [layer.get_weights()[0] for layer in layers]
    sizes = [len(weight) for weight in weights] + [outputSize]

    data, row, col = [], [], [] 
    offset = 0
    for layer_num in range(len(sizes) - 1, 0, -1):
        old_offset = offset
        offset += sizes[layer_num]
        for j in range(0, sizes[layer_num]):
        
            weight = weights[layer_num - 1]
            weightPlus = weight * (weight > 0)
            
            normalizeFactor = 0
            for i in range(sizes[layer_num - 1]):
                normalizeFactor += weightPlus[i][j]
            for i in range(sizes[layer_num - 1]):
                x, y = i + offset, j + old_offset
                if weightPlus[i][j] != 0:
                    data.append(np.log((weightPlus[i][j] / normalizeFactor)**(-1)))
                    row.append(y)
                    col.append(x)

    return csr_matrix((data, (row, col))) 

In [162]:
relevance = get_relevance(model)

## Неориентированный вариант

In [173]:
graph = GraphGeodesicDistance(directed=False).fit_transform(relevance)

In [174]:
from gtda.homology import VietorisRipsPersistence
# 
VietorisRipsPersistence(metric="precomputed").fit_transform_plot(X_ggd)

array([[[0.        , 0.97818154, 0.        ],
        [0.        , 1.10521019, 0.        ],
        [0.        , 1.22804523, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        , 0.        , 1.        ]]])

## Ориентированный вариант

In [165]:
from gtda.homology import FlagserPersistence
X_ggd = GraphGeodesicDistance(directed=True).fit_transform(relevance)
FlagserPersistence(directed=True).fit_transform_plot(X_ggd)

array([[[0.        , 0.97818154, 0.        ],
        [0.        , 1.10521019, 0.        ],
        [0.        , 1.22804523, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        , 0.        , 1.        ]]])

In [181]:
model_name_func =  lambda cut: modelDir + "first"+str(firstSize)+"second"+str(secondSize)+"output"+str(outputSize) + "cut_by" + str(cut) + ".h5"

In [182]:
model_name2 = model_name_func(1.5) 

In [183]:
model2 = models.load_model(model_name2, compile = False)

In [184]:
relevance2 = get_relevance(model)
X_ggd2 = GraphGeodesicDistance(directed=True).fit_transform(relevance2)
FlagserPersistence(directed=True).fit_transform_plot(X_ggd2)

array([[[0.        , 0.97818154, 0.        ],
        [0.        , 1.10521019, 0.        ],
        [0.        , 1.22804523, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        ,        inf, 0.        ],
        [0.        , 0.        , 1.        ]]])